-- Fraud Risk Analytics
-- PostgreSQL schema for the synthetic payments dataset.

CREATE TABLE customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signup_at TIMESTAMPTZ NOT NULL,
    country_code CHAR(2) NOT NULL,
    kyc_status VARCHAR(20) NOT NULL,
    risk_tier VARCHAR(10) NOT NULL,

    CONSTRAINT chk_kyc_status
        CHECK (kyc_status IN ('verified', 'pending', 'rejected')),

    CONSTRAINT chk_risk_tier
        CHECK (risk_tier IN ('low', 'medium', 'high'))
);

CREATE TABLE devices (
    device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_type VARCHAR(20) NOT NULL,
    operating_system VARCHAR(30) NOT NULL,
    first_seen_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT chk_device_type
        CHECK (device_type IN ('mobile', 'desktop', 'tablet'))
);

CREATE TABLE account_devices (
    customer_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_account_devices
        PRIMARY KEY (customer_id, device_id),

    CONSTRAINT fk_account_devices_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),

    CONSTRAINT fk_account_devices_device
        FOREIGN KEY (device_id)
        REFERENCES devices(device_id),

    CONSTRAINT chk_account_device_dates
        CHECK (last_seen_at >= first_seen_at)
);

CREATE TABLE transactions (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,
    transaction_at TIMESTAMPTZ NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    amount_eur NUMERIC(12,2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    ip_country_code CHAR(2) NOT NULL,

    CONSTRAINT fk_transactions_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),

    CONSTRAINT fk_transactions_device
        FOREIGN KEY (device_id)
        REFERENCES devices(device_id),

    CONSTRAINT chk_transaction_type
        CHECK (transaction_type IN ('deposit', 'payment', 'withdrawal')),

    CONSTRAINT chk_transaction_status
        CHECK (status IN ('successful', 'failed', 'pending')),

    CONSTRAINT chk_transaction_amount
        CHECK (amount_eur > 0)
);
